name: sky_background
description: The sky is beautiful! Now you can transfer a piece of the sky to your application using this library.
version: 0.1.2
homepage: https://github.com/RenatFakhrutdinov/sky_background

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/cloud1.png
    - lib/assets/cloud2.png
    - lib/assets/cloud3.png
    - lib/assets/cloud4.png
    - lib/assets/cloud5.png