name: sky_background
description: Beautiful background with floating clouds
version: 0.1.0
homepage: https://github.com/RenatFakhrutdinov/sky_background

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/cloud1.png
    - lib/assets/cloud2.png
    - lib/assets/cloud3.png
    - lib/assets/cloud4.png
    - lib/assets/cloud5.png